services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: biaoqing-postgres
    environment:
      POSTGRES_DB: biaoqing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-extensions.sql:/docker-entrypoint-initdb.d/init-extensions.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [
      "postgres",
      "-c", "shared_preload_libraries=pg_trgm,vector"
    ]